<div class="card">
  <div class="card-header bg-warning-subtle">Team</div>
  <div class="card-body">
    <div class="mb-3">
      <h6 class="mb-1">Share about the key members of your team.</h6>
    </div>

    <div class="row g-3">
      <div class="col-md-6">
        <label class="form-label">Title</label>
        <input type="text" id="team_title" class="form-control" placeholder="Section Title">
      </div>
      <div class="col-md-6">
        <label class="form-label">Description</label>
        <textarea id="team_desc" class="form-control" rows="2" placeholder="Team Description"></textarea>
      </div>
    </div>

    <hr>

    <div id="teamList" class="vstack gap-4">
      <!-- Team member rows generated by JS -->
    </div>

    <div class="d-flex justify-content-end mt-3">
      <a href="/?action=store&step=about" class="btn btn-outline-secondary me-2">Back</a>
      <button class="btn btn-success">Save</button>
    </div>
  </div>
</div>

<script>
(function(){
  const teamContainer = document.getElementById('teamList');
  const members = 5; // show 5 members for now

  function memberRow(idx){
    return `
    <div class="row g-3 align-items-start" data-team="${idx}">
      <div class="col-12 text-muted mb-1">Person ${idx}</div>
      <div class="col-md-3">
        <div class="border rounded position-relative" style="min-height:140px;background:#f8f9fa;">
          <div id="teamPrev${idx}" class="d-flex align-items-center justify-content-center h-100 text-muted">+ Upload Image</div>
          <button type="button" class="btn btn-sm btn-outline-danger position-absolute top-0 end-0 m-1 d-none" id="teamRemove${idx}"><i class="bi bi-x"></i></button>
        </div>
        <input type="file" class="form-control mt-2" id="teamFile${idx}" accept="image/png,image/jpeg,image/webp" />
        <div class="form-text">PNG/JPG/WEBP up to 8MB.</div>
      </div>
      <div class="col-md-4">
        <label class="form-label">Name</label>
        <input type="text" id="team_name${idx}" class="form-control" placeholder="Name">
      </div>
      <div class="col-md-4">
        <label class="form-label">Designation</label>
        <input type="text" id="team_role${idx}" class="form-control" placeholder="Designation">
      </div>
      <div class="col-md-1 d-flex align-items-end">
        <button class="btn btn-primary w-100" id="teamUpload${idx}">Upload</button>
      </div>
    </div>`;
  }

  for (let i=1;i<=members;i++) teamContainer.insertAdjacentHTML('beforeend', memberRow(i));

  // Load existing images
  async function loadImage(i){
    try {
      const r = await fetch('/?action=salesConfig&subaction=getTeamImage&idx=' + i);
      const d = await r.json();
      const prev = document.getElementById('teamPrev'+i);
      const rm = document.getElementById('teamRemove'+i);
      if (d && d.exists && d.url) {
        prev.innerHTML = `<img src="${d.url}" class="img-fluid rounded" alt="Team ${i}">`;
        rm.classList.remove('d-none');
      } else {
        prev.textContent = '+ Upload Image';
        rm.classList.add('d-none');
      }
    } catch(e) { console.warn('team load', i, e); }
  }
  for (let i=1;i<=members;i++) loadImage(i);

  // Load stored names/designations and section headings
  (async function loadTeam(){
    try{
      const keys=['team_title','team_desc'];
      for(let i=1;i<=members;i++){ keys.push(`team_name${i}`, `team_role${i}`); }
      const r=await fetch('/?action=salesConfig&subaction=getStoreSettings&keys='+encodeURIComponent(keys.join(',')));
      const d=await r.json();
      if(d){
        const set=(id)=>{ const el=document.getElementById(id); if(el && d[id]) el.value=d[id]; };
        keys.forEach(set);
      }
    }catch(e){ console.warn('team load failed', e); }
  })();

  // Upload handlers
  for (let i=1;i<=members;i++){
    const btn = document.getElementById('teamUpload'+i);
    btn?.addEventListener('click', async ()=>{
      const inp = document.getElementById('teamFile'+i);
      if (!inp || !inp.files || !inp.files[0]){ alert('Select an image for Person '+i); return; }
      const fd = new FormData();
      fd.append('idx', i);
      fd.append('image', inp.files[0]);
      try {
        btn.disabled = true; btn.textContent='Uploading...';
        const r = await fetch('/?action=salesConfig&subaction=uploadTeamImage', { method:'POST', body: fd });
        const d = await r.json();
        if (!r.ok || d.error) throw new Error(d.error || 'Upload failed');
        await loadImage(i);
      } catch(err){ alert('Upload error: ' + (err?.message || 'Failed')); }
      finally { btn.disabled=false; btn.textContent='Upload'; }
    });
    const rm = document.getElementById('teamRemove'+i);
    rm?.addEventListener('click', async ()=>{
      if (!confirm('Remove image for Person '+i+'?')) return;
      try {
        rm.disabled = true; rm.textContent='...';
        const r = await fetch('/?action=salesConfig&subaction=removeTeamImage', { method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body: 'idx='+encodeURIComponent(i) });
        const d = await r.json();
        if (!r.ok || d.error) throw new Error(d.error || 'Failed');
        await loadImage(i);
      } catch(err){ alert('Remove error: ' + (err?.message || 'Failed')); }
      finally { rm.disabled=false; rm.innerHTML='<i class="bi bi-x"></i>'; }
    });
  }
})();

// Save team data (title, desc, names, roles)
document.addEventListener('click', async (e)=>{
  if (e.target && e.target.matches('.btn.btn-success')){
    // Only intercept our Save button in this section
  }
});

document.querySelector('.card .btn.btn-success')?.addEventListener('click', async (ev)=>{
  if (!ev.currentTarget) return;
  // Build payload
  const payload={
    team_title: document.getElementById('team_title')?.value||'',
    team_desc: document.getElementById('team_desc')?.value||''
  };
  for(let i=1;i<=5;i++){
    payload[`team_name${i}`]=document.getElementById('team_name'+i)?.value||'';
    payload[`team_role${i}`]=document.getElementById('team_role'+i)?.value||'';
  }
  try{
    const r=await fetch('/?action=salesConfig&subaction=saveStoreSettings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
    const d=await r.json(); if(!r.ok||d.error) throw new Error(d.error||'Save failed');
    alert('Team saved');
  }catch(err){ alert('Save error: '+(err?.message||'Failed')); }
});
</script>
